### ISSUE TITLE
Unity plugin cannot startup on agent side

### ISSUE THREAD

**Issue by ArtemBahniuk** [JetBrains/teamcity-unity-plugin#80]
TeamCity server version: 2022.04.4 (build 108763)
Plugin version: 1.0.0

After agent startup I found this stack trace in logs:

```
[2023-02-22 22:25:10,042]   WARN - inLoader$TeamCityPluginContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainAutowireCandidateResolver' defined in URL [jar:file:/Users/admin/BuildAgent/lib/common-impl.jar!/META-INF/teamcity-global-spring-candidate-resolver.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [jetbrains.buildServer.unity.UnityToolProvider] for bean with name 'jetbrains.buildServer.unity.UnityToolProvider#0' defined in Byte array resource [plugin: teamcity-unity-agent#plugin-unity-agent.jar!/META-INF/build-agent-plugin-unity.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier
[2023-02-22 22:25:10,042]   WARN - gins.spring.SpringPluginLoader - Error occurred during destroying beans for plugin jetbrains.buildServer.plugins.PluginData@206ccc1b: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [jetbrains.buildServer.unity.UnityToolProvider] for bean with name 'jetbrains.buildServer.unity.UnityToolProvider#0' defined in Byte array resource [plugin: teamcity-unity-agent#plugin-unity-agent.jar!/META-INF/build-agent-plugin-unity.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier (enable debug to see stacktrace)
[2023-02-22 22:25:10,054]  ERROR - gins.spring.SpringPluginLoader - Error loading plugin 'teamcity-unity-agent': Failed to initialize spring context: Error creating bean with name 'mainAutowireCandidateResolver' defined in URL [jar:file:/Users/admin/BuildAgent/lib/common-impl.jar!/META-INF/teamcity-global-spring-candidate-resolver.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [jetbrains.buildServer.unity.UnityToolProvider] for bean with name 'jetbrains.buildServer.unity.UnityToolProvider#0' defined in Byte array resource [plugin: teamcity-unity-agent#plugin-unity-agent.jar!/META-INF/build-agent-plugin-unity.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mainAutowireCandidateResolver' defined in URL [jar:file:/Users/admin/BuildAgent/lib/common-impl.jar!/META-INF/teamcity-global-spring-candidate-resolver.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [jetbrains.buildServer.unity.UnityToolProvider] for bean with name 'jetbrains.buildServer.unity.UnityToolProvider#0' defined in Byte array resource [plugin: teamcity-unity-agent#plugin-unity-agent.jar!/META-INF/build-agent-plugin-unity.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:628) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring.jar:5.3.18]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:196) ~[spring.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring.jar:5.3.18]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring.jar:5.3.18]
	at jetbrains.buildServer.plugins.spring.SpringPluginLoader.pluginClassesLoaded(SpringPluginLoader.java:124) ~[common-impl.jar:?]
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_351]
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157) ~[common.jar:?]
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:136) ~[common.jar:?]
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82) ~[common.jar:?]
	at com.sun.proxy.$Proxy24.pluginClassesLoaded(Unknown Source) ~[?:?]
	at jetbrains.buildServer.plugins.PluginManagerImpl$5.visitPlugin(PluginManagerImpl.java:441) ~[common-impl.jar:?]
	at jetbrains.buildServer.plugins.PluginsCollection$1.run(PluginsCollection.java:98) ~[common-impl.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [jetbrains.buildServer.unity.UnityToolProvider] for bean with name 'jetbrains.buildServer.unity.UnityToolProvider#0' defined in Byte array resource [plugin: teamcity-unity-agent#plugin-unity-agent.jar!/META-INF/build-agent-plugin-unity.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1545) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:704) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:674) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring.jar:5.3.18]
	at jetbrains.buildServer.spring.candidates.MainAutowireCandidateResolver.setBeanFactory(MainAutowireCandidateResolver.java:102) ~[common-impl.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1826) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring.jar:5.3.18]
	... 23 more
Caused by: java.lang.NoClassDefFoundError: jetbrains/buildServer/agent/config/AgentParametersSupplier
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_351]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_351]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_351]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_351]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_351]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_351]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_351]
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:80) ~[common-impl.jar:?]
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:46) ~[common-impl.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_351]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_351]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_351]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:469) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1607) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1534) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:704) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:674) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring.jar:5.3.18]
	at jetbrains.buildServer.spring.candidates.MainAutowireCandidateResolver.setBeanFactory(MainAutowireCandidateResolver.java:102) ~[common-impl.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1826) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring.jar:5.3.18]
	... 23 more
Caused by: java.lang.ClassNotFoundException: Class 'jetbrains.buildServer.agent.config.AgentParametersSupplier' was not found
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:92) ~[common-impl.jar:?]
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:46) ~[common-impl.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_351]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_351]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_351]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_351]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_351]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_351]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_351]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_351]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_351]
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.doLoadClass(TeamCityClassLoader.java:80) ~[common-impl.jar:?]
	at jetbrains.buildServer.plugins.classLoaders.TeamCityClassLoader.loadClass(TeamCityClassLoader.java:46) ~[common-impl.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_351]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_351]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_351]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:469) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1607) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1534) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:704) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:674) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring.jar:5.3.18]
	at jetbrains.buildServer.spring.candidates.MainAutowireCandidateResolver.setBeanFactory(MainAutowireCandidateResolver.java:102) ~[common-impl.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1826) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791) ~[spring.jar:5.3.18]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring.jar:5.3.18]
	... 23 more
```
	
It looks like my agent does not have enough libraries to start the unity plugin. Are there some variants to reduce this problem instead of updating the server with agents?

**Comment by ArtemBahniuk** [comment]
Or maybe it can be conflicts with some other plugins?
