### ISSUE TITLE
Unable to locate tool unity in system, despite tool being installed

### ISSUE THREAD

**Issue by tiritto** [JetBrains/teamcity-unity-plugin#81]
I'm trying to make automated builds for my project in Unity, but whatever I do, my Build always fails at "Cannot start build runner" with the following error:
```
jetbrains.buildServer.agent.ToolCannotBeFoundException: Unable to locate tool unity in system. Please make sure correct Unity binary tool is installed
    at jetbrains.buildServer.unity.UnityToolProvider.getUnity(UnityToolProvider.kt:135)
    at jetbrains.buildServer.unity.UnityToolProvider.getUnity(UnityToolProvider.kt:119)
    at jetbrains.buildServer.unity.UnityRunnerBuildService.makeProgramCommandLine(UnityRunnerBuildService.kt:87)
    at jetbrains.buildServer.unity.CommandExecutionAdapter.makeProgramCommandLine(CommandExecutionAdapter.kt:66)
    at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:81)
    at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:289)
    at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:61)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:27)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:177)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:162)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:112)
    at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:52)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:33)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
    at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
    at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:91)
    at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:65)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:345)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:63)
    at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:294)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

Some extra information:
- TeamCity is running on Docker, Linux machine.
- Agent is running on separate Docker (but is correctly detected and registered).
- Unity files are packed from Windows machine and uploaded in TeamCity - Settings - Tools, as instructed.
- I've tried removing "f1" ending from version name, but it changed nothing.
- I've tried following [this tutorial from JetBrains](https://www.youtube.com/watch?v=Sh_BRCw7prc) but still run into this issue.

What might be the issue? What else should I check?

**Comment by lesley29** [comment]
Issue discussion takes place on YouTrack [TW-80106](https://youtrack.jetbrains.com/issue/TW-80106)
